### ISSUE TITLE
crash when close browser

### ISSUE THREAD

**Issue by markuman** [eirikb/weecloud#14]
When i just close the browser, weecloud crashed

TypeError: Object #<Object> has no method 'disconnect'
    at Socket.<anonymous> (/home/markuman/weecloud/lib/weecloud.js:113:12)
    at Socket.EventEmitter.emit [as $emit](events.js:95:17)
    at Socket.onDisconnect (/home/markuman/weecloud/node_modules/socket.io/lib/socket.js:153:10)
    at SocketNamespace.handleDisconnect (/home/markuman/weecloud/node_modules/socket.io/lib/namespace.js:229:46)
    at Manager.onClientDisconnect (/home/markuman/weecloud/node_modules/socket.io/lib/manager.js:501:29)
    at WebSocket.Transport.end (/home/markuman/weecloud/node_modules/socket.io/lib/transport.js:467:20)
    at WebSocket.Transport.onSocketEnd (/home/markuman/weecloud/node_modules/socket.io/lib/transport.js:147:8)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

or am i blind and haven't found an exist button?

**Comment by eirikb** [comment]
Have you updated weechat.js?
In both master branch and latest tag weechat.js version is 0.0.15, which should include the disconnect function, [ref](https://github.com/eirikb/weechat.js/blob/master/src/weechat.js#L108).  
Try updating with npm, and also just manually check the version /code in node_modules.

**Comment by markuman** [comment]
i did a new git clone. now it works. thx
